on: [push]
jobs:
  hello_world:
    runs-on: ubuntu-latest
    name: Yes
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run our action
        uses: ./
        id: delete_stuff
        with:
          last_commit_age_days: 9
      - name: Get output
        run:  echo "The time was ${{ steps.delete_stuff.outputs.deleted_branches }}"
