name: Quick tests against our own repository

on:
  push:

  # Allow workflow to be manually run from the GitHub UI
  workflow_dispatch:
jobs:
  check_dry_run_no_branches:
    runs-on: ubuntu-latest
    name: Runs the action with no ignore branches
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build action container
        run: docker build -t action_container .

      - name: Run our action
        run: |
          docker run --rm action_container \
            --ignore-branches=deletable-but-ignored \
            --last-commit-age-days=9 \
            --dry-run=yes \
            --github-token="${{ github.token }}"

